config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {:registrations => "registrations" }
  
  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  root 'categories#index'

  get '/user', to: 'users#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates :title, :description, :price, presence: true
  validates :price, format: {with: /\A\d+(?:\.\d{0,2})?\z/}

  def average_rating
    if self.reviews.size > 0
      self.reviews.average(:rating).round(1)
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates :content, :rating, :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products

  validates :firstname, :lastname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]

  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
    if !current_user.admin?
      redirect_to new_user_session_path
    end
  end

  def edit
    if !current_user.admin?
      redirect_to new_user_session_path
    end
  end

  def create
    if current_user.admin?
      self.category = Category.new(category_params)

      if category.save
        redirect_to category, notice: 'Category was successfully created.'
      else
        render action: 'new'
      end
    else
      redirect_to new_user_session_path
    end  
  end

  def update
    if current_user.admin?
      if category.update(category_params)
        redirect_to category, notice: 'Category was successfully updated.'
      else
        render action: 'edit'
      end
    else
      redirect_to new_user_session_path
    end  
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def admin?
      if current_user.admin
        true
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]

  def index
  end

  def show
  end

  def new
  end

  def edit
    if current_user != Product.find(params[:id]).user
      redirect_to category_product_url(category, product)
      flash[:error] = 'You are not allowed to edit this product.'
    end
  end

  def create
    self.product = Product.new(product_params)
    self.product.user_id = current_user.id

    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if current_user == Product.find(params[:id]).user
      if self.product.update(product_params)
        redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
      else
        render action: 'edit'
      end
    else
      redirect_to category_product_url(category, product)
      flash[:error] = 'You are not allowed to edit this product.'
    end
  end

  # DELETE /products/1
  def destroy
    if current_user.products
      product.destroy
      redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
    else
      redirect_to category_product_url(category, product)
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :email, :password) }
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:product)

  def edit
  end

  def create
    self.review = Review.new(review_params)
    self.review.user_id = current_user.id

    if review.save
      product.reviews << review
      redirect_to category_product_path(product.category, product), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_path(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  expose(:user)
  expose(:product)
  expose(:products)
  expose(:reviews)
  expose(:category)

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: "Name"

  = f.submit 'Save', class: 'btn btn-success'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', category, class: 'btn btn-info'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/index.html.haml
%h1 Listing categories

.container.col-lg-6 
  %table.table
    %tr
      %th Name
      %th

    - categories.each do |category|
      %tr
        %td.col-lg-4= category.name
        %td.col-lg-2
          = link_to 'Show', category_products_path(category), class: "btn btn-info btn-xs"
          - if user_signed_in?
            - if current_user.admin
              = link_to 'Edit', edit_category_path(category), class: "btn btn-warning btn-xs"
              = link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"


  %br

  - if user_signed_in?
    - if current_user.admin
      = link_to 'New Category', new_category_path, class: "btn btn-success btn-sm"

app/views/categories/new.html.haml
%h1 New category

= render 'form'

%br

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = link_to category.name, category

%p
  - category.products.each do |product|
    = product.title

%p
  %h3 New product
  = render 'products/form'

= link_to 'Edit', edit_category_path(category), class: 'btn btn-warning'

= link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %span.navbar-brand #{AppConfig.workshops_name}
        %p.navbar-text.navbar-right
          - if user_signed_in?
            = link_to current_user.email, user_path(current_user)
            = link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-warning btn-sm"
          - else
            = link_to "Log in", new_user_session_path, class: "btn btn-success btn-sm"
            = link_to "Sign up", new_user_registration_path, class: "btn btn-info btn-sm"
    .container-fluid
      .row
        .col-lg-12
          = yield

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  - if product.errors.any?
    #error_explanation
      %h2= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: "Title"
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', placeholder: "Description"
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control', placeholder: "0.00"

  = f.submit 'Save', class: 'btn btn-success'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'
%br
= link_to 'Show', category_product_path(category, product), class: 'btn btn-info btn-xs'

= link_to 'Back', category_path(category), class: 'btn btn-primary btn-xs'

app/views/products/index.html.haml
= link_to "Categories", categories_path, class: 'label label-default'

%h1 Listing products

.container.col-lg-12
  %table.table
    %tr
      %th.col-lg-3 Title
      %th.col-lg-6 Description
      %th.col-lg-1 Price
      %th.col-lg-2

    - category.products.each do |product|
      %tr
        %td= product.title
        %td= product.description
        %td= product.price
        %td
          = link_to 'Show', category_product_path(product.category, product), class: "btn btn-info btn-xs"
          - if user_signed_in?
            - if current_user.id == product.user_id
              = link_to 'Edit', edit_category_product_path(product.category, product), class: "btn btn-warning btn-xs"
              = link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"        

  %br

  = link_to "Add product", new_category_product_path, class: 'btn btn-success'

app/views/products/new.html.haml
%b Category: 
= category.name

%h1 New product

= render 'form'

%br

= link_to 'Back', category_products_path, class: 'btn btn-primary'

app/views/products/show.html.haml
%p#notice= notice
%p#error= flash[:error]

%p
  %h3
    = product.title
    .span.label.label-danger.label-as-badge= product.average_rating
%p
  %b Description:
  = product.description
%p
  %b Price:
  = product.price

%p
  %b Category
  = link_to product.category.name, categories_path, class: 'label label-default'

- if user_signed_in?
  - if current_user.id = product.user_id
    = link_to 'Edit', edit_category_product_path(category.id, product.id), class: 'btn btn-warning btn-xs'

= link_to 'Back', category_products_path, class: 'btn btn-primary btn-xs'

%h3 Reviews

- if user_signed_in?
  = render 'reviews/form'

= render reviews

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    #error_explanation
      %h2= "#{pluralize(review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - review.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.input :rating, collection: 1..5, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-success'

app/views/reviews/_review.html.haml
%br
%p
  %span.badge= review.rating
  %em= review.author
%p= review.content

app/views/users/index.html.haml
.container 
  %div.row
    %div.col-lg-3
      %div.media-body
        %h4.media-heading
          = current_user.firstname
          = current_user.lastname
        %h5
          .glyphicon.glyphicon-envelope
          = current_user.email

    %div.col-lg-9
      %h4 User Products:
      %table.table.table-striped
        %tr
          %th Product name
          %th Description
          %th Price
          %th.col-lg-3
        - current_user.products.each do |product|
          %tr
            %td= product.title
            %td= product.description
            %td= product.price
            %td
              = link_to 'Show', category_product_path(product.category, product), class: "btn btn-info btn-xs"
              = link_to 'Edit', edit_category_product_path(product.category, product), class: "btn btn-warning btn-xs"
              = link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?'},class: "btn btn-danger btn-xs"

.container
  .div.col-lg-3
  .div.col-lg-9
    %h4 User Reviews
    %table.table.table-striped
      %tr
        %th Product
        %th Review
        %th Rating
        %th Date
      - current_user.reviews.last(5).reverse.each do |review|
        %tr
          %td= review.product.title
          %td= review.content
          %td
            .span.badge= review.rating
          %td= review.created_at.strftime("%d-%m-%Y")